# This workflow will create two folders with a zip of the extension ready to deploy to Chrome and Firefox.

name: "New release"

on:
  push:
    branches: [ "main" ]

jobs:
  chrome:
    name: generate chrome
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
         repository: ${{ github.event.pull_request.head.repo.full_name }}
         ref: ${{ github.event.pull_request.head.ref }}
      - name: Manifest Version
        run: sed -i '2s/.*/    "manifest_version":3,/' manifest.json
      - name: Zip folder
        run: zip release/testing.zip icons/ main.js manifest.json
        
      - name: Modifiy the specific files using action
        uses: action-owner/action-repo@ref

      - name: Commit and push changes
        run: |
          git config --global user.name "thePeras"
          git config --global user.email "jtopereira@gmail.com"

          git add -A
          git commit -m "commit message"
          git push
