# This workflow will create two folders with a zip of the extension ready to deploy to Chrome and Firefox.

name: "New release"

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: build-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
        with:
         repository: ${{ github.event.pull_request.head.repo.full_name }}
         ref: ${{ github.event.pull_request.head.ref }}

      - name: Creating folder
        run: mkdir release/${{ github.event.head_commit.message }}

      - name: Manifest version to 3
        run: sed -i '2s/.*/    "manifest_version":3,/' manifest.json
      - name: Building Chrome zip folder
        run: zip release/${{ github.event.head_commit.message }}/copy-code-extension-chrome v${{ github.event.head_commit.message }}.zip icons/ main.js manifest.json

      - name: Manifest version to 2
        run: sed -i '2s/.*/    "manifest_version":2,/' manifest.json
      - name: Building Firefox zip folder
        run: zip release/${{ github.event.head_commit.message }}/copy-code-extension-firefox v${{ github.event.head_commit.message }}.zip icons/ main.js manifest.json
        
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release/${{ github.event.head_commit.message }}/copy-code-extension-firefox v${{ github.event.head_commit.message }}.zip, release/${{ github.event.head_commit.message }}/copy-code-extension-chrome v${{ github.event.head_commit.message }}.zip"
          token: ${{ secrets.YOUR_GITHUB_TOKEN }}